name: ejercicio2

on:
  schedule:
  - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Test Unit
        run: mvn test -Dtest=ReviewServiceUnitaryTest

      - name: Test Integracion
        run: mvn test -Dtest=OpenLibraryServiceIntegrationTest

      - name: Test REST
        run: mvn test -Dtest=RestTest
        
      - name: Test Selenium
        run: mvn test -Dtest=SeleniumTest
